Config: Enable suffix path matching
Starting from Spring Boot 2.0, suffix path matching is not enabled by
default anymore[1], so we must enable it manually.

Both setUseSuffixPatternMatch and favorPathExtension calls allow URLs
with extensions to be resolved to the same mapping as without extension.

In Airsonic's case, this is necessary, because a lot of our mappings assume
this behavior (for example "/home.view" URL to a "/home" mapping, or the
entire Subsonic REST API controller).

This fixes crashes when accessing almost all pages (which expect to use
.view URLs), and also fixes the following REST API tests:

    [ERROR] Failures:
    [ERROR]   AirsonicRestApiJukeboxIntTest>AbstractAirsonicRestApiJukeboxIntTest.jukeboxStartActionTest:202->AbstractAirsonicRestApiJukeboxIntTest.performStartAction:282 Status expected:<200> but was:<404>
    [ERROR]   AirsonicRestApiJukeboxIntTest>AbstractAirsonicRestApiJukeboxIntTest.jukeboxStopActionTest:225->AbstractAirsonicRestApiJukeboxIntTest.performStartAction:282 Status expected:<200> but was:<404>
    [ERROR]   AirsonicRestApiJukeboxLegacyIntTest.jukeboxStartActionTest:48->AbstractAirsonicRestApiJukeboxIntTest.jukeboxStartActionTest:202->AbstractAirsonicRestApiJukeboxIntTest.performStartAction:282 Status expected:<200> but was:<404>
    [ERROR]   AirsonicRestApiJukeboxLegacyIntTest.jukeboxStopActionTest:56->AbstractAirsonicRestApiJukeboxIntTest.jukeboxStopActionTest:225->AbstractAirsonicRestApiJukeboxIntTest.performStartAction:282 Status expected:<200> but was:<404>

[1] https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#spring-mvc-path-matching-default-behavior-change